version: '3.8'

services:
  go-proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2020:2020" 
    container_name: go-proxy-server-container
    restart: always
