version: '3.8'

services:
  go-proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2080:80"
      - "4043:443"
    container_name: go-proxy-server-container
    volumes:
      - ./certs:/app/certs
      - ./.env:/app/.env
    restart: unless-stopped
